[application]

# App (Project) Name
name = "personal_web"

[web.app]

# HTML title tag content
title = "personal_web"

# include `assets` in web platform
[web.resource]

# Include assets directory
base = "assets"

# Additional CSS style files
style = ["assets/tailwind.css", "assets/styling/main.css"]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
